<?php
/**
 * ExportManager class for ModPress plugin.
 * @package ModPress
 * @subpackage Admin\Manager\Tools
 * @since 1.0.0
 */
namespace ModPress\Admin\Manager\Tools;

use ModPress\Admin\Manager\Manager;
use ModPress\Includes\Functions\Helpers\FormFieldHelper;
use ModPress\Includes\Functions\Helpers\UrlHelper;

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

final class ImportManager extends Manager {
    /**
     * Constructor for the ImportManager class.
     *
     * @since 1.0.0
     */
    public function __construct() {
    }

    /**
     * Render the JSON import form below the tools settings form.
     *
     * @return void
     */
    public function render(): void {
        ?>
        <form method="post" action="<?php echo esc_url( UrlHelper::admin_action( 'modpress_import' ) ); ?>" enctype="multipart/form-data" class="card modpress-import-form shadow-sm mt-4">
            <?php echo wp_kses_post( FormFieldHelper::input( 'action', 'modpress_import', [ 'type' => 'hidden' ] ) ); ?>
            <?php wp_nonce_field( 'modpress_import' ); ?>
            <div class="card-body"><?php echo wp_kses_post( FormFieldHelper::label( 'modpress-import-file', __( 'Import ModPress JSON', 'modpress' ), [ 'description' => __( 'Select a JSON export generated by ModPress.', 'modpress' ), 'tooltip' => __( 'Importing replaces matching ModPress data with the contents of the file.', 'modpress' ), 'tooltip_icon' => 'fa-file-import' ] ) ); ?><?php echo wp_kses_post( FormFieldHelper::input( 'modpress_import_file', '', [ 'id' => 'modpress-import-file', 'type' => 'file', 'class' => 'mb-3', 'accept' => 'application/json,.json', 'required' => true ] ) ); ?><?php echo wp_kses_post( FormFieldHelper::button( __( 'Import JSON', 'modpress' ), [ 'type' => 'submit', 'class' => 'btn-primary' ] ) ); ?></div>
        </form>
        <?php
    }
}